# Generated by Django 2.0.1 on 2018-01-12 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CardDatas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ot', models.IntegerField(blank=True)),
                ('alias', models.IntegerField(blank=True)),
                ('setcode', models.IntegerField(blank=True)),
                ('card_type', models.IntegerField(db_column='type', default=0)),
                ('attack', models.IntegerField(db_column='atk', default=0)),
                ('defense', models.IntegerField(db_column='def', default=0)),
                ('level', models.IntegerField(blank=True)),
                ('race', models.IntegerField(blank=True)),
                ('attribute', models.IntegerField(blank=True)),
                ('category', models.IntegerField(blank=True)),
            ],
            options={
                'db_table': 'datas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CardTexts',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('desc', models.TextField(blank=True)),
                ('str1', models.TextField(blank=True)),
                ('str2', models.TextField(blank=True)),
                ('str3', models.TextField(blank=True)),
                ('str4', models.TextField(blank=True)),
                ('str5', models.TextField(blank=True)),
                ('str6', models.TextField(blank=True)),
                ('str7', models.TextField(blank=True)),
                ('str8', models.TextField(blank=True)),
                ('str9', models.TextField(blank=True)),
                ('str10', models.TextField(blank=True)),
                ('str11', models.TextField(blank=True)),
                ('str12', models.TextField(blank=True)),
                ('str13', models.TextField(blank=True)),
                ('str14', models.TextField(blank=True)),
                ('str15', models.TextField(blank=True)),
                ('str16', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'texts',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='card',
            name='datas_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ygo_db.CardDatas'),
        ),
        migrations.AddField(
            model_name='card',
            name='texts_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ygo_db.CardTexts'),
        ),
    ]
