# Generated by Django 2.0.1 on 2018-01-12 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ygo_db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='datas_id',
        ),
        migrations.RemoveField(
            model_name='card',
            name='texts_id',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
