# Generated by Django 2.0.1 on 2018-01-15 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ygo_db', '0002_auto_20180112_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardAttribute',
            fields=[
                ('id', models.ForeignKey(db_column='attribute', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ygo_db.CardDatas')),
                ('str_attribute', models.CharField(choices=[(1, 'EARTH'), (2, 'WATER'), (4, 'FIRE'), (8, 'WIND'), (16, 'LIGHT'), (32, 'DARK'), (64, 'DIVINE')], max_length=10)),
            ],
        ),
    ]
