# Generated by Django 2.0.1 on 2018-01-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ygo_db', '0004_auto_20180115_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardattribute',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
