# Generated by Django 2.0.1 on 2018-01-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ygo_db', '0006_auto_20180115_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardattribute',
            name='str_attribute',
        ),
        migrations.AddField(
            model_name='cardattribute',
            name='attribute',
            field=models.CharField(default='EARTH', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cardattribute',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
