# Generated by Django 2.0.1 on 2018-01-25 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ygo_db', '0007_auto_20180115_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardattribute',
            old_name='attribute',
            new_name='attri',
        ),
        migrations.AlterField(
            model_name='cardattribute',
            name='id',
            field=models.ForeignKey(db_column='attribute', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ygo_db.CardDatas'),
        ),
    ]
