# Generated by Django 2.0.1 on 2018-01-25 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ygo_db', '0008_auto_20180125_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardattribute',
            name='id',
        ),
        migrations.DeleteModel(
            name='CardAttribute',
        ),
    ]
